language: objective-c

osx_image: xcode8.2
xcode_project: Morse.xcodeproj # path to your xcodeproj folder
xcode_scheme: Morse
xcode_sdk: iphonesimulator10.1

script:
- xcodebuild clean -project Morse.xcodeproj -scheme Morse -sdk iphonesimulator -destination 'platform=iOS Simulator,id=3B5E817B-744D-4086-AAB0-55CB35A17717,OS=10.1' build test | xcpretty -c --test --color
